image: docker:git

stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/aali361/telegram:latest

build-image:
  stage: build
  only:
    - master@aali361/telegram
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_RELEASE_IMAGE || true
    - docker build --cache-from $CONTAINER_RELEASE_IMAGE -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE

deploy-image:
  stage: deploy
  only:
    - master@aali361/telegram
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host target\n\tStrictHostKeyChecking no\n\tConnectTimeout 10\n\tConnectionAttempts 10\n\tHostName 78.47.57.106\n\tUser mohammad\n\tPort 22\n" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - scp docker-compose-pro.yml Telegram_api_nginx.conf mng-api.sh .docpasswd doc.json target:/var/www/igap_inf/
    - ssh target "cd /var/www/igap_inf/ && ./mng-api.sh up"
